//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarModsManager.Assets {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StarModsManager.Assets.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add To Tag.
        /// </summary>
        public static string AddToTag {
            get {
                return ResourceManager.GetString("AddToTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Api:.
        /// </summary>
        public static string ApiLabel {
            get {
                return ResourceManager.GetString("ApiLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Api Settings.
        /// </summary>
        public static string ApiSettings {
            get {
                return ResourceManager.GetString("ApiSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Theme.
        /// </summary>
        public static string AppTheme {
            get {
                return ResourceManager.GetString("AppTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Backup.
        /// </summary>
        public static string AutoBackup {
            get {
                return ResourceManager.GetString("AutoBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Check Updates:.
        /// </summary>
        public static string AutoCheckUpdates {
            get {
                return ResourceManager.GetString("AutoCheckUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Select.
        /// </summary>
        public static string AutoSelect {
            get {
                return ResourceManager.GetString("AutoSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        public static string Available {
            get {
                return ResourceManager.GetString("Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Folder.
        /// </summary>
        public static string BackupFolder {
            get {
                return ResourceManager.GetString("BackupFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Delete Folder: {0}.
        /// </summary>
        public static string CannotDeleteFolder {
            get {
                return ResourceManager.GetString("CannotDeleteFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot load mod: {0}.
        /// </summary>
        public static string CannotLoadMod {
            get {
                return ResourceManager.GetString("CannotLoadMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Color.
        /// </summary>
        public static string ChangeColor {
            get {
                return ResourceManager.GetString("ChangeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Picture.
        /// </summary>
        public static string ChangePic {
            get {
                return ResourceManager.GetString("ChangePic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Update.
        /// </summary>
        public static string CheckUpdate {
            get {
                return ResourceManager.GetString("CheckUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Version.
        /// </summary>
        public static string CurrentVersion {
            get {
                return ResourceManager.GetString("CurrentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string Custom {
            get {
                return ResourceManager.GetString("Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Color.
        /// </summary>
        public static string CustomColor {
            get {
                return ResourceManager.GetString("CustomColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark1.
        /// </summary>
        public static string Dark1 {
            get {
                return ResourceManager.GetString("Dark1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark2.
        /// </summary>
        public static string Dark2 {
            get {
                return ResourceManager.GetString("Dark2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark3.
        /// </summary>
        public static string Dark3 {
            get {
                return ResourceManager.GetString("Dark3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug Mode:.
        /// </summary>
        public static string DebugMode {
            get {
                return ResourceManager.GetString("DebugMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inner Delay.
        /// </summary>
        public static string Delay {
            get {
                return ResourceManager.GetString("Delay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Download Items.
        /// </summary>
        public static string DeleteAll {
            get {
                return ResourceManager.GetString("DeleteAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependencies.
        /// </summary>
        public static string Dependencies {
            get {
                return ResourceManager.GetString("Dependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string DependencyIsRequired {
            get {
                return ResourceManager.GetString("DependencyIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Version.
        /// </summary>
        public static string DependencyMinVersion {
            get {
                return ResourceManager.GetString("DependencyMinVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependency Missing.
        /// </summary>
        public static string DependencyMissing {
            get {
                return ResourceManager.GetString("DependencyMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        public static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable.
        /// </summary>
        public static string Disable {
            get {
                return ResourceManager.GetString("Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Latest Version.
        /// </summary>
        public static string DownloadLatestVersion {
            get {
                return ResourceManager.GetString("DownloadLatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Manager.
        /// </summary>
        public static string DownloadManager {
            get {
                return ResourceManager.GetString("DownloadManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string DownloadManagerLabel {
            get {
                return ResourceManager.GetString("DownloadManagerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NexusMods.
        /// </summary>
        public static string DownloadPageLabel {
            get {
                return ResourceManager.GetString("DownloadPageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloads.
        /// </summary>
        public static string Downloads {
            get {
                return ResourceManager.GetString("Downloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        public static string Enable {
            get {
                return ResourceManager.GetString("Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endorsements.
        /// </summary>
        public static string Endorsements {
            get {
                return ResourceManager.GetString("Endorsements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter URL.
        /// </summary>
        public static string EnterURL {
            get {
                return ResourceManager.GetString("EnterURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find a mod folder that meets the requirements in the target folder.
        /// </summary>
        public static string ErrorFoldersMsg {
            get {
                return ResourceManager.GetString("ErrorFoldersMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred:.
        /// </summary>
        public static string ErrorOccurred {
            get {
                return ResourceManager.GetString("ErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching mod download link....
        /// </summary>
        public static string FetchingModLink {
            get {
                return ResourceManager.GetString("FetchingModLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name.
        /// </summary>
        public static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Api Key.
        /// </summary>
        public static string GetApiKeyButton {
            get {
                return ResourceManager.GetString("GetApiKeyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Cookies.
        /// </summary>
        public static string GetCookies {
            get {
                return ResourceManager.GetString("GetCookies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To view cookies in Chrome, open Chrome Settings (right-click on your browser window) &gt; Inspect &gt; Applications &gt; Storage &gt; Cookies, and select the website you want to see cookies in Chrome. Here you can see, edit, or delete cookies in Chrome..
        /// </summary>
        public static string GetCookiesText {
            get {
                return ResourceManager.GetString("GetCookiesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting mod download links....
        /// </summary>
        public static string GetDownloadUrl {
            get {
                return ResourceManager.GetString("GetDownloadUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Models.
        /// </summary>
        public static string GetModels {
            get {
                return ResourceManager.GetString("GetModels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header.
        /// </summary>
        public static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to Install Language Pack.
        /// </summary>
        public static string I18NInstallFailed {
            get {
                return ResourceManager.GetString("I18NInstallFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing mod for translation pack: {0}.
        /// </summary>
        public static string I18NInstallNotFound {
            get {
                return ResourceManager.GetString("I18NInstallNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed Localization Package: {0}.
        /// </summary>
        public static string I18NInstallSuccess {
            get {
                return ResourceManager.GetString("I18NInstallSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install All.
        /// </summary>
        public static string InstallAll {
            get {
                return ResourceManager.GetString("InstallAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed {0}({1})&quot;.
        /// </summary>
        public static string InstalledModWithVersion {
            get {
                return ResourceManager.GetString("InstalledModWithVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing....
        /// </summary>
        public static string Installing {
            get {
                return ResourceManager.GetString("Installing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing Mods.
        /// </summary>
        public static string InstallingMods {
            get {
                return ResourceManager.GetString("InstallingMods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is ContentPack For {0}.
        /// </summary>
        public static string IsContentPackFor {
            get {
                return ResourceManager.GetString("IsContentPackFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lang Key.
        /// </summary>
        public static string LangKey {
            get {
                return ResourceManager.GetString("LangKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Comment.
        /// </summary>
        public static string LastComment {
            get {
                return ResourceManager.GetString("LastComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest Updated.
        /// </summary>
        public static string LatestUpdated {
            get {
                return ResourceManager.GetString("LatestUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest Version.
        /// </summary>
        public static string LatestVersion {
            get {
                return ResourceManager.GetString("LatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light1.
        /// </summary>
        public static string Light1 {
            get {
                return ResourceManager.GetString("Light1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light2.
        /// </summary>
        public static string Light2 {
            get {
                return ResourceManager.GetString("Light2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light3.
        /// </summary>
        public static string Light3 {
            get {
                return ResourceManager.GetString("Light3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lines.
        /// </summary>
        public static string Lines {
            get {
                return ResourceManager.GetString("Lines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        public static string MainPageLabel {
            get {
                return ResourceManager.GetString("MainPageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to manifest.json file not found.
        /// </summary>
        public static string ManifestFileNotFound {
            get {
                return ResourceManager.GetString("ManifestFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message:.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string ModAuthor {
            get {
                return ResourceManager.GetString("ModAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string ModDescription {
            get {
                return ResourceManager.GetString("ModDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Models:.
        /// </summary>
        public static string ModelsLabel {
            get {
                return ResourceManager.GetString("ModelsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod file not found or cannot be downloaded.
        /// </summary>
        public static string ModFileNotFound {
            get {
                return ResourceManager.GetString("ModFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod installed successfully.
        /// </summary>
        public static string ModInstallSuccess {
            get {
                return ResourceManager.GetString("ModInstallSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest Version.
        /// </summary>
        public static string ModLatestVersion {
            get {
                return ResourceManager.GetString("ModLatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod Name.
        /// </summary>
        public static string ModName {
            get {
                return ResourceManager.GetString("ModName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nexus ID.
        /// </summary>
        public static string ModNexusId {
            get {
                return ResourceManager.GetString("ModNexusId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Auto Select Mod Folder.
        /// </summary>
        public static string ModsDirNotFound {
            get {
                return ResourceManager.GetString("ModsDirNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod Tools.
        /// </summary>
        public static string ModTools {
            get {
                return ResourceManager.GetString("ModTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UniqueID.
        /// </summary>
        public static string ModUniqueId {
            get {
                return ResourceManager.GetString("ModUniqueId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpdateKeys.
        /// </summary>
        public static string ModUpdateKeys {
            get {
                return ResourceManager.GetString("ModUpdateKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string ModVersion {
            get {
                return ResourceManager.GetString("ModVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple mods archive not supported yet:.
        /// </summary>
        public static string MultiModUpdateNotSupport {
            get {
                return ResourceManager.GetString("MultiModUpdateNotSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network connection error, please check network settings.
        /// </summary>
        public static string NetworkErrorMsg {
            get {
                return ResourceManager.GetString("NetworkErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Download.
        /// </summary>
        public static string NewDownload {
            get {
                return ResourceManager.GetString("NewDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nexus Api State:.
        /// </summary>
        public static string NexusApiState {
            get {
                return ResourceManager.GetString("NexusApiState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nexus Cookie State:.
        /// </summary>
        public static string NexusCookieState {
            get {
                return ResourceManager.GetString("NexusCookieState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-NexusPremium users please fill in this field to enable download feature, like: token_invalidated_at=context; nexusmods_session=context; fwroute=context; nexusmods_session_refresh=content; cf_clearance=content.
        /// </summary>
        public static string NexusModsCookieWaterMark {
            get {
                return ResourceManager.GetString("NexusModsCookieWaterMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nexus Premium required for direct mod download. Please use web download.
        /// </summary>
        public static string NexusPremiumRequired {
            get {
                return ResourceManager.GetString("NexusPremiumRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All mods are up to date.
        /// </summary>
        public static string NoModToUpdate {
            get {
                return ResourceManager.GetString("NoModToUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any pictures in the mod page.
        /// </summary>
        public static string NoPics {
            get {
                return ResourceManager.GetString("NoPics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice.
        /// </summary>
        public static string Notice {
            get {
                return ResourceManager.GetString("Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a mod archive/package.
        /// </summary>
        public static string NotModArchive {
            get {
                return ResourceManager.GetString("NotModArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Download Page.
        /// </summary>
        public static string OpenDownloadPage {
            get {
                return ResourceManager.GetString("OpenDownloadPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open File.
        /// </summary>
        public static string OpenFile {
            get {
                return ResourceManager.GetString("OpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Folder.
        /// </summary>
        public static string OpenFolder {
            get {
                return ResourceManager.GetString("OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit Mod Webpage.
        /// </summary>
        public static string OpenUrl {
            get {
                return ResourceManager.GetString("OpenUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Canceled.
        /// </summary>
        public static string OperationCanceled {
            get {
                return ResourceManager.GetString("OperationCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others.
        /// </summary>
        public static string Others {
            get {
                return ResourceManager.GetString("Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overall Progress.
        /// </summary>
        public static string OverallProgress {
            get {
                return ResourceManager.GetString("OverallProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-set Colors.
        /// </summary>
        public static string PreSetColors {
            get {
                return ResourceManager.GetString("PreSetColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prompt Text:.
        /// </summary>
        public static string PromptText {
            get {
                return ResourceManager.GetString("PromptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proofread.
        /// </summary>
        public static string ProofreadPageLabel {
            get {
                return ResourceManager.GetString("ProofreadPageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random.
        /// </summary>
        public static string Random {
            get {
                return ResourceManager.GetString("Random", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove From Tag.
        /// </summary>
        public static string RemoveFromTag {
            get {
                return ResourceManager.GetString("RemoveFromTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resize.
        /// </summary>
        public static string Resize {
            get {
                return ResourceManager.GetString("Resize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response:.
        /// </summary>
        public static string Response {
            get {
                return ResourceManager.GetString("Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart required for changes to take effect.
        /// </summary>
        public static string RestartRequired {
            get {
                return ResourceManager.GetString("RestartRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Current Size.
        /// </summary>
        public static string SaveCurrentSize {
            get {
                return ResourceManager.GetString("SaveCurrentSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for Mod.....
        /// </summary>
        public static string SearchModText {
            get {
                return ResourceManager.GetString("SearchModText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SelectFolder.
        /// </summary>
        public static string SelectFolderButton {
            get {
                return ResourceManager.GetString("SelectFolderButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Accent Color.
        /// </summary>
        public static string SettingAppAccentColor {
            get {
                return ResourceManager.GetString("SettingAppAccentColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set a custom accent color for the App.
        /// </summary>
        public static string SettingAppAccentColorDes {
            get {
                return ResourceManager.GetString("SettingAppAccentColorDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mods Directory.
        /// </summary>
        public static string SettingDir {
            get {
                return ResourceManager.GetString("SettingDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the directory where your mods are stored.
        /// </summary>
        public static string SettingDirDes {
            get {
                return ResourceManager.GetString("SettingDirDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flow Direction.
        /// </summary>
        public static string SettingFlowDirection {
            get {
                return ResourceManager.GetString("SettingFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the current app flow direction.
        /// </summary>
        public static string SettingFlowDirectionDes {
            get {
                return ResourceManager.GetString("SettingFlowDirectionDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nexus Api.
        /// </summary>
        public static string SettingNexusApi {
            get {
                return ResourceManager.GetString("SettingNexusApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Api Key:.
        /// </summary>
        public static string SettingNexusApiKey {
            get {
                return ResourceManager.GetString("SettingNexusApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used for downloading mods from Nexus and retrieving mod information.
        /// </summary>
        public static string SettingNexusApiKeyDes {
            get {
                return ResourceManager.GetString("SettingNexusApiKeyDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cookies:.
        /// </summary>
        public static string SettingNexusCookies {
            get {
                return ResourceManager.GetString("SettingNexusCookies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsButton {
            get {
                return ResourceManager.GetString("SettingsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the current app theme.
        /// </summary>
        public static string SettingThemeDes {
            get {
                return ResourceManager.GetString("SettingThemeDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window Size.
        /// </summary>
        public static string SettingWindowSize {
            get {
                return ResourceManager.GetString("SettingWindowSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save current app window size.
        /// </summary>
        public static string SettingWindowSizeDes {
            get {
                return ResourceManager.GetString("SettingWindowSizeDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort.
        /// </summary>
        public static string Sort {
            get {
                return ResourceManager.GetString("Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Code.
        /// </summary>
        public static string SourceCode {
            get {
                return ResourceManager.GetString("SourceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Text.
        /// </summary>
        public static string SourceText {
            get {
                return ResourceManager.GetString("SourceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch All Mods.
        /// </summary>
        public static string SwitchLabelMods {
            get {
                return ResourceManager.GetString("SwitchLabelMods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol.
        /// </summary>
        public static string Symbol {
            get {
                return ResourceManager.GetString("Symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol matching error found, please fix on the proofreading page.
        /// </summary>
        public static string SymbolError {
            get {
                return ResourceManager.GetString("SymbolError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Accent Color.
        /// </summary>
        public static string SystemAccentColor {
            get {
                return ResourceManager.GetString("SystemAccentColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Lang.
        /// </summary>
        public static string TargetLang {
            get {
                return ResourceManager.GetString("TargetLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translated Text.
        /// </summary>
        public static string TargetText {
            get {
                return ResourceManager.GetString("TargetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a temporary page..
        /// </summary>
        public static string TempPage {
            get {
                return ResourceManager.GetString("TempPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thread Internal Error.
        /// </summary>
        public static string ThreadInternalError {
            get {
                return ResourceManager.GetString("ThreadInternalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to install {0}.
        /// </summary>
        public static string ToInstall {
            get {
                return ResourceManager.GetString("ToInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing mod localization package, installation path: {0}.
        /// </summary>
        public static string ToInstallI18N {
            get {
                return ResourceManager.GetString("ToInstallI18N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translate.
        /// </summary>
        public static string TranslatePageLabel {
            get {
                return ResourceManager.GetString("TranslatePageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translate Service State:.
        /// </summary>
        public static string TranslateServiceState {
            get {
                return ResourceManager.GetString("TranslateServiceState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translating....
        /// </summary>
        public static string Translating {
            get {
                return ResourceManager.GetString("Translating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translating Settings.
        /// </summary>
        public static string TranslatingSettings {
            get {
                return ResourceManager.GetString("TranslatingSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation failed.
        /// </summary>
        public static string TranslationError {
            get {
                return ResourceManager.GetString("TranslationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check if your API is correct..
        /// </summary>
        public static string TranslationErrorMsg {
            get {
                return ResourceManager.GetString("TranslationErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mismatch symbols found. Open proofreading window?.
        /// </summary>
        public static string TranslationMismatch {
            get {
                return ResourceManager.GetString("TranslationMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translate Not Available, please check Translate Settings.
        /// </summary>
        public static string TranslationNotAvailable {
            get {
                return ResourceManager.GetString("TranslationNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation prompt text:.
        /// </summary>
        public static string TranslationPrompt {
            get {
                return ResourceManager.GetString("TranslationPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation Stopped.
        /// </summary>
        public static string TranslationStopped {
            get {
                return ResourceManager.GetString("TranslationStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trending.
        /// </summary>
        public static string Trending {
            get {
                return ResourceManager.GetString("Trending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turbo Mode.
        /// </summary>
        public static string TurboMode {
            get {
                return ResourceManager.GetString("TurboMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to translate.
        /// </summary>
        public static string UnableTrans {
            get {
                return ResourceManager.GetString("UnableTrans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unavailable.
        /// </summary>
        public static string Unavailable {
            get {
                return ResourceManager.GetString("Unavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique Downloads.
        /// </summary>
        public static string UniqueDownloads {
            get {
                return ResourceManager.GetString("UniqueDownloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsaved.
        /// </summary>
        public static string Unsaved {
            get {
                return ResourceManager.GetString("Unsaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have unsaved changes. Would you like to save them?.
        /// </summary>
        public static string UnsavedTip {
            get {
                return ResourceManager.GetString("UnsavedTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untranslated entries.
        /// </summary>
        public static string UnTransCounts {
            get {
                return ResourceManager.GetString("UnTransCounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Available.
        /// </summary>
        public static string UpdateAvailable {
            get {
                return ResourceManager.GetString("UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version {0} available.
        /// </summary>
        public static string UpdateAvailableContent {
            get {
                return ResourceManager.GetString("UpdateAvailableContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string UpdatePageLabel {
            get {
                return ResourceManager.GetString("UpdatePageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url:.
        /// </summary>
        public static string UrlLabel {
            get {
                return ResourceManager.GetString("UrlLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Custom Accent Color?.
        /// </summary>
        public static string UseCustomAccentColorDes {
            get {
                return ResourceManager.GetString("UseCustomAccentColorDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With Prompt within Settings.
        /// </summary>
        public static string WithPrompt {
            get {
                return ResourceManager.GetString("WithPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
